name: MamaBear
values:
  - key: baseUrl
    value: 'https://mamabear-backend-production.up.railway.app'
    enabled: true
    type: default
  - key: accessToken
    value: ''
    enabled: true
    type: default
  - key: refreshToken
    value: ''
    enabled: true
    type: default
  - key: userId
    value: ''
    enabled: true
    type: default
  - key: productId
    value: ''
    enabled: true
    type: default
  - key: resetToken
    value: ''
    enabled: true
    type: default
  - key: verificationToken
    value: ''
    enabled: true
    type: default
