name: ci

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
    timeout-minutes: 5
    env:
      RUNNER_OS: Linux
      PGHOST: localhost
      PGDATABASE: mamabear
      PGUSERNAME: regencode
      PGPASSWORD: pgpasswordregencode
    steps:
    - name: Add PostgreSQL binaries to PATH
      shell: bash
      run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$PGBIN" >> $GITHUB_PATH
          elif [ "$RUNNER_OS" == "Linux" ]; then
            echo "$(pg_config --bindir)" >> $GITHUB_PATH
          fi
    - name: Initialize and start PostgreSQL
      shell: bash
      run: |
        echo "initializing database cluster..."

        # convert backslashes to forward slashes in runner_temp for windows git bash
        export runner_temp="/tmp"
        export pghost="${runner_temp//\\//}/postgres"
        export pgdata="$pghost/pgdata"
        mkdir -p "$pgdata"

        # initdb requires file for password in non-interactive mode
        export pwfile="$runner_temp/pwfile"
        echo "postgres" > "$pwfile"
        initdb --pgdata="$pgdata" --username="postgres" --pwfile="$pwfile"

        echo "starting postgresql..."
        echo "unix_socket_directories = '$pghost'" >> "$pgdata/postgresql.conf"
        pg_ctl -D $pgdata start

        echo "creating user..."
        psql --host "$pghost" --username="postgres" --dbname="postgres" --command="create user $pgusername password '$pgpassword'" --command="\du"

        echo "creating database..."
        createdb --owner="$PGUSERNAME" --username="postgres" "$PGDATABASE"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx prisma migrate build
        npx prisma generate
        npx nest start
